### ISSUE TITLE
A "readme-generic"?

### ISSUE THREAD

**Issue by jamen** [generate/generate-readme#3]
I'm developing a C++ project, and used `gen readme`, and noticed the npm stuff in the output.

I would like a README formatted like `readme-node`, but excluding npm information for projects outside of Node.js/JavaScript...  Just plain with universal information, like the name, description, author, license, etc.

Do you think that is outside the scope of this package?

**Comment by doowb** [comment]
Try the following command:

``` sh
$ gen readme:minimal
```

This will run the `minimal` task that uses the [minimal template](https://github.com/generate/generate-readme/blob/master/templates/minimal.md)

**Comment by jamen** [comment]
Ahh, I see.  I took a look at that template earlier, and the table made me think it created [something like this](https://github.com/jamen/gulp-pug/blob/671714d09e9ccd291489f22988bbc40fe8db40ec/README.md).  But I see now that works.  Thanks.  :>

**Comment by jonschlinkert** [comment]
I'd love a pr for another template too. My main goal was to get this published and working, next improve templates :)
