### ISSUE TITLE
The min/minimal task doesn't create README.

### ISSUE THREAD

**Issue by jamen** [generate/generate-readme#4]
A few days ago this seemed to be working fine for me.

What is documented doesn't seem to work anymore:

```
% gen readme:min            
[16:36:50] starting generate
[16:36:50] ✔ running tasks: [ 'readme:min' ]
Cannot find task: "min" in generator: "readme"
```

Additionally, `readme:minimal` seems to work (it goes through the prompts and exits fine) but doesn't actually create the `README.md` file.

**Comment by jamen** [comment]
Same can be said for the `readme:node` task it seems.

**Comment by jonschlinkert** [comment]
what about just `gen readme`?

**Comment by jamen** [comment]
Same effect.  Prompts and exits fine, but no README is created.

**Comment by jonschlinkert** [comment]
Did you try re-installing generate and generate-readme?

**Comment by jamen** [comment]
Yeah,

`generate` is at:

``` javascript
"version": "0.10.0"
```

And `generate-readme`:

``` javascript
"version": "0.2.2"
```

**Comment by jonschlinkert** [comment]
Ok, thanks I'll take a look

**Comment by jamen** [comment]
@jonschlinkert Could this be an issue with an update in `generate`? I don't think any generators are creating files for me.  Tried with `generate-package` and `generate-license` just now.

**Comment by jonschlinkert** [comment]
that seems strange, I haven't had any other reports about generators not working, and they work fine for me. I wonder if it's something else. Do you have any custom templates defined?

**Comment by jamen** [comment]
I don't think so (wasn't aware you could make custom ones).

They seem to work fine at first, it goes all through the prompts.  But then just never creates the files.  

Like this:

```
bloop [master] % gen readme:minimal
[20:09:19] starting generate
[20:09:20] ✔ running tasks: [ 'readme:minimal' ]
[20:09:20] starting readme 
[20:09:20] starting readme:minimal task 
[20:09:20] starting readme:readme-minimal task 
? Project name? bloop
? Project description? A cross-platform notification server.
? Project license? MIT
? Author's name? Jamen Marz
? Author's URL? 
bloop [master] % ls
bloop [master] % 
```

**Comment by jonschlinkert** [comment]
> wasn't aware you could make custom ones

yeah, just create a `~/templates` folder (in user home) and add a template with the same name as the template used by the generator.

I'm looking into it now

**Comment by jamen** [comment]
So, I upgraded to Node v6.3.1 recently, which is what made me reinstall all my global modules, include these ones.

Just now, I tried switching back to the old node and old global modules I was using (Node v6.2.2 with `generate` v0.9) using `nvm`, and everything worked fine, and the `README.md` generated.

I then tried to upgrade `generate@latest` and `generate-readme@latest` on Node v6.2.2 and I'm getting the issue again.

**Comment by jonschlinkert** [comment]
are you saying the issue is happening with generate 0.10.0 or with node v6.2.2? Sounds like generate, just want to be sure

**Comment by jamen** [comment]
With generate 0.10 it seems.

**Comment by jonschlinkert** [comment]
k thx I'm still investigating. trying to clear everything and test each version.

what OS and file system are you using?

**Comment by jamen** [comment]
I use Linux Mint, and by file system if you mean the type then `ext4`.

**Comment by jonschlinkert** [comment]
yeah that helps, thanks.

**Comment by jamen** [comment]
Not sure if this is helpful, but I just noticed that it doesn't exit fine on 0.10.  When I downgrade to the working versions (below 0.10) it prompts the "finished" parts.  It doesn't do that with 0.10 for me:

```
bloop [master●] % gen --version
[20:59:34] starting generate
generate v0.9.8

bloop [master●] % gen readme:minimal 
# ...
[20:53:50] finished readme:readme-minimal task 2s
[20:53:50] finished readme:minimal task 2s
[20:53:50] finished readme ✔ 2s
```

**Comment by jonschlinkert** [comment]
I'm getting the same error now. I think I know what it is

**Comment by jonschlinkert** [comment]
Figured it out. I'll push up a fix in the next couple of minutes

**Comment by jamen** [comment]
Awesome, thanks a bunch.  :+1:

**Comment by jonschlinkert** [comment]
No prob, thanks for working through it with me. I think it's fixed now, can you confirm by reinstalling?

**Comment by jonschlinkert** [comment]
btw, the last comment you made about exiting is exactly what tipped me off. Thank you.  It's why I put the comment about "What you should see in the terminal" in readmes https://github.com/generate/generate-readme#run

**Comment by jamen** [comment]
Yup, it seems it work now.  I tested other generators and they work as well.  Nice job.
